comment/urls.py
from django.urls import path, re_path
from comment.views import *

app_name = 'comment'

urlpatterns = [
    re_path(r'^create/(?P<pid>[0-9]+)/(?P<slug>[-a-zA-Z0-9_]+)/(?P<parent>[0-9]+)?', create, name='create'),
    path('delete/<int:id>', delete, name='delete'),
]

src/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

from blog.sitemaps import BlogSitemap, CategoriesSitemap
from src import settings
from website.sitemaps import StaticViewSitemap

sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap,
    'categories': CategoriesSitemap
}

urlpatterns = [
    path('administors/', admin.site.urls),
    path('auth', include('customuser.urls')),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('comment/', include('comment.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', include('robots.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path("", include("allauth.urls"))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comment/models.py
from django.db import models

from blog.models import Post
from customuser.models import User
from jalali_date import datetime2jalali


class Approved(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Status.APPROVED)


# Create your models here.
class Status(models.TextChoices):
    APPROVED = 'ap', 'Approved'
    REJECTED = 're', 'rejected'


class Comment(models.Model):
    body = models.TextField(max_length=700)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.REJECTED)

    # RELATIONS
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=False)

    # DATE TIMES
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # MANAGERS
    default_manager = models.Manager()
    objects = Approved()

    @property
    def jalali_created_at(self):
        return datetime2jalali(self.created_at).strftime('%Y/%m/%d')

    class Meta:
        ordering = ['-created_at']
        get_latest_by = ['-created_at']

comment/forms.py
from django import forms
from django.shortcuts import get_object_or_404

from blog.middlewares import get_request
from blog.models import Post
from comment.models import Comment


class CommentForm(forms.ModelForm):
    body = forms.CharField(max_length=700, min_length=1, required=True, error_messages={
        'min_length': 'طول عبارت جست و جو باید بیش از 3 کاراکتر باشد.'
    })
    post = forms.IntegerField(required=True)
    parent = forms.IntegerField(required=False)

    author = forms.IntegerField(required=False)

    class Meta:
        model = Comment
        fields = ['body', 'post', 'parent', 'author']

    def clean_author(self):
        if get_request().user.is_authenticated:
            return get_request().user

        return None

    def clean_post(self):
        if self.cleaned_data["post"]:
            return get_object_or_404(Post.objects.all(), pk=self.cleaned_data['post'])

        return None

    def clean_parent(self):
        if self.cleaned_data["parent"]:
            return get_object_or_404(Comment.objects.all(), pk=self.cleaned_data['parent'])

        return None

comment/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views.decorators.http import require_POST

from comment.forms import CommentForm
from comment.models import Comment


# Create your views here.
@require_POST
def create(request, pid, slug, parent=None):
    data = request.POST.copy()
    data['post'] = pid
    data['parent'] = parent
    form = CommentForm(data)

    if form.is_valid():
        form.save()
        messages.success(request, 'نظر شما با موفقیت دریافت شد و پس از تایید منتشر می شود.')

    return redirect(reverse('blog:show-post', kwargs={'slug': slug, 'pid': pid}))


@require_POST
@login_required
def delete(request, id):
    comment = get_object_or_404(Comment.objects.select_related('post').select_related('author').all(), pk=id)
    author = comment.author
    post = comment.post

    if author.id != request.user.id:
        raise Exception('403!')

    comment.delete()
    messages.success(request, 'نظر شما حذف شد.')
    return redirect(reverse('blog:show-post', kwargs={'slug': post.slug, 'pid': post.id}))

templates/comment/comment.html
<div x-data="{ showReply: false, openAreYouSureModal: false }"
     class="flex flex-col w-full text-base rounded-sm {% if comment.parent %} bg-teal-50 {% else %} bg-teal-100 {% endif %}">

    <div class="flex flex-row w-full mx-3 mt-3 items-center justify-between">
        <div class="flex flex-row justify-center items-center text-primary">
            <span class="mdi mdi-account-circle-outline text-5xl"></span>
            <span class="truncate text-primary mr-1 font-bold" dir="ltr">
                    {{ comment.author.username }}
            </span>
        </div>
        {% if request.user.is_authenticated %}

            <div class="flex flex-row {% if not comment.parent %} ml-8 {% endif %} ml-4">
                {% if comment.author.id == request.user.id %}
                    <a title="حذف نظر"
                       @click="openAreYouSureModal=true"
                       class="text-red cursor-pointer ml-3">
                        <span class="mdi mdi-trash-can text-3xl"></span>
                    </a>
                {% endif %}

                {% if not comment.parent %}
                    <a title="پاسخ"
                       @click="showReply=!showReply"
                       class="text-secondary cursor-pointer">
                        <span class="mdi  mdi-reply-all text-3xl"></span>
                    </a>
                {% endif %}

            </div>

        {% endif %}

    </div>
    <div class="w-full text-sm lg:text-base break-words px-4 my-2 text-primary leading-relaxed">
        {{ comment.body|safe }}
    </div>
    {% if request.user.is_authenticated %}
        {% if not comment.parent %}
            <div class="flex justify-center py-3" x-show="showReply" x-cloak>
                <form class="flex flex-col w-full justify-center items-center h-auto px-4"
                      method="POST"
                      action="{% url 'comment:create' pid=post.id slug=post.slug parent=comment.id %}">
                    {% csrf_token %}
                    <textarea class="form-textarea border-4 bg-yellow-lightest w-full"
                              name="body"
                              required
                              placeholder="پاسخی برای این نظر بنویسید..."
                              rows="7"
                    ></textarea>
                    <div class="flex flex-row w-full items-start justify-between mt-3">
                        <div>
                        </div>
                        <div>
                            <button @click.prevent="showReply=false"
                                    class="h-10 w-32 bg-secondary rounded-lg text-white ml-2">
                                <span class="mx-3 font-bold">انصراف</span>
                            </button>
                            <button class="h-10 w-32 bg-secondary rounded-lg text-white">
                                <span class="mx-3 font-bold">ثبت پاسخ</span>
                            </button>
                        </div>

                    </div>

                </form>
            </div>
        {% endif %}
    {% endif %}
    {% include "components/are-you-sure.html" with deletable_id=comment.id delete_route_name="comment:delete" message='از حذف این نظر مطمئن هستید؟' %}

</div>

templates/comment/comments.html
<div class="w-full flex flex-col h-auto justify-center items-center">
    <div class="w-full lg:w-10/12 flex flex-col justify-center items-center px-2 my-6">
        {% for comment in comments %}

            <div class="flex flex-col items-center justify-center w-full my-1">

            {% include 'comment/comment.html' with comment=comment request=request post=post %}

          {% for reply in comment.comment_set.all %}

                {% include 'comment/comment.html' with comment=reply request=request post=post %}

          {% endfor %}

            </div>

        {% endfor %}
   </div>
</div>

{#@foreach($parentComments as $comment)#}
{#        <livewire:single-product.comment :comment="$comment" parentId="0" :product="$product" bg="bg-gray-200 mt-4" />#}

{#    @endforeach#}