blog/urls.py
from django.urls import path
from blog.views import *

app_name = 'blog'

urlpatterns = [
    path('<str:slug>-p<int:pid>', show, name='show-post'),
    path('<str:slug>-c<int:cid>', show_category_posts, name='show-category-posts'),
    path('all', all_posts, name='all-posts'),
    path('bookmark', bookmark, name='bookmark'),
    path('bookmarks', bookmarks, name='bookmarks'),
    path('rate/<int:pid>/<int:rate>', rate, name='rate')
]

customuser/urls.py
from django.urls import path
from customuser.views import *

app_name = 'customuser'

urlpatterns = [
    path('', login_or_register, name='login-or-register'),
    path('logout', logout_user, name='logout'),
    path('back-from-google', back_from_google, name='back-from-google')
]

src/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

from blog.sitemaps import BlogSitemap, CategoriesSitemap
from src import settings
from website.sitemaps import StaticViewSitemap

sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap,
    'categories': CategoriesSitemap
}

urlpatterns = [
    path('administors/', admin.site.urls),
    path('auth', include('customuser.urls')),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('comment/', include('comment.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', include('robots.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path("", include("allauth.urls"))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website.views import *

app_name = 'website'

urlpatterns = [
    path('', index, name='home'),
    path('contact', contact, name='contact')
]

templates/layouts/footer.html
{% load static %}
<footer class="container mx-auto w-full">
    <div
            class="flex flex-col w-full items-center justify-between border-t border-grey-lighter py-10 sm:flex-row sm:py-12"
    >
        <div class="flex flex-col items-center justify-center sm:flex-row">
            <a href="/" class="sm:mr-6">
                <img src="{% static 'img/logo.svg' %}" alt="logo"/>
            </a>
            <p class="pt-5 mr-2.5 font-body font-light text-primary dark:text-white sm:pt-0">
                ©2022 sutta
            </p>
        </div>
        <div class="flex items-center justify-center pt-5 sm:mr-0 sm:pt-0">

            <a href="https://www.linkedin.com/in/sajjad-nasiri-422869210/" target="_blank">
                <i
                        class="text-4xl text-primary dark:text-white pl-5 hover:text-secondary dark:hover:text-secondary transition-colors mdi mdi-linkedin"
                ></i>
            </a>
            <a href="https://github.com/sajjadnasiribrn" target="_blank">
                <i
                        class="text-4xl text-primary dark:text-white pl-5 hover:text-secondary dark:hover:text-secondary transition-colors mdi mdi-github"
                ></i>
            </a>
            <a href="https://t.me/suttablog" target="_blank">
                <i
                        class="text-4xl text-primary dark:text-white pl-5 hover:text-secondary dark:hover:text-secondary transition-colors mdi mdi-telegram"
                ></i>
            </a>
            <a href="https://instagram.com/suttablog?igshid=ZDdkNTZiNTM=" target="_blank">
                <i
                        class="text-4xl text-primary dark:text-white pl-5 hover:text-secondary dark:hover:text-secondary transition-colors mdi mdi-instagram"
                ></i>
            </a>


        </div>
    </div>
</footer>

templates/layouts/header.html
{% load static %}
<nav class="container mx-auto">
    <div class="flex items-center justify-between py-6 lg:py-10">
        <a href="{{ request.scheme }}://{{ request.META.HTTP_HOST }}{% url 'website:home' %}" class="flex items-center">
      <span class="mr-2">
        <img src="{{ request.scheme }}://{{ request.META.HTTP_HOST }}{% static 'img/logo.svg' %}" alt="logo"/>
      </span>
            <p
                    class="font-body text-2xl font-bold text-primary dark:text-white lg:block mr-2"
            >
                سوتا
            </p>
        </a>
        <div class="flex flex-row items-center lg:hidden">
            <i
                    class="mdi pl-8 cursor-pointer text-3xl text-primary dark:text-white"
                    @click="themeSwitch()"
                    :class="isDarkMode ? 'mdi-white-balance-sunny' : 'mdi-weather-night'"
            ></i>

            <button @click="isMobileMenuOpen = true"
                    class="mdi mdi-menu text-3xl text-primary dark:text-white"
            >
            </button>
        </div>
        <div class="hidden lg:block">
            <ul class="flex items-center">

                <li class="group relative mr-6 mb-1">
                    <div
                            class="absolute left-0 bottom-0 z-20 h-0 w-full opacity-75 transition-all group-hover:h-2 group-hover:bg-yellow"
                    ></div>
                    <a
                            href="{{ request.scheme }}://{{ request.META.HTTP_HOST }}{% url "blog:all-posts" %}"
                            class="relative z-30 block px-2 font-body text-base font-medium text-primary transition-colors group-hover:text-green dark:text-white dark:group-hover:text-secondary"
                    >جدیدترین</a
                    >
                </li>

                <li class="group relative mr-6 mb-1">
                    <div
                            class="absolute left-0 bottom-0 z-20 h-0 w-full opacity-75 transition-all group-hover:h-2 group-hover:bg-yellow"
                    ></div>
                    <a
                            href="/contact"
                            class="relative z-30 block px-2 font-body text-base font-medium text-primary transition-colors group-hover:text-green dark:text-white dark:group-hover:text-secondary"
                    >تماس با ما</a
                    >
                </li>

                {% if request.user.is_authenticated %}
            <li class="group relative mr-6 mb-1">
                    <div
                            class="absolute left-0 bottom-0 z-20 h-0 w-full opacity-75 transition-all group-hover:h-2 group-hover:bg-yellow"
                    ></div>
                    <a
                            href="{{ request.scheme }}://{{ request.META.HTTP_HOST }}{% url "blog:bookmarks" %}"
                            class="relative z-30 block px-2 font-body text-base font-medium text-primary transition-colors group-hover:text-green dark:text-white dark:group-hover:text-secondary"
                    >
                        ذخیره‌شده‌ها
                    </a>
                </li>
                {% endif %}

                <li class="group relative mr-6 mb-1 flex flex-row">
                    <div
                            class="absolute left-0 bottom-0 z-20 h-0 w-full opacity-75 transition-all group-hover:h-2 group-hover:bg-yellow"
                    ></div>
                    {% if not request.user.is_authenticated %}
                        <a
                                href="{{ request.scheme }}://{{ request.META.HTTP_HOST }}{% url "customuser:login-or-register" %}"
                                class="relative z-30 block px-2 font-body text-base font-medium text-primary transition-colors group-hover:text-green dark:text-white dark:group-hover:text-secondary"
                        >ورود / ثبت نام</a>
                    {% else %}

                        <a      onclick="event.preventDefault(); document.getElementById('logout-form').submit();"
                                class="flex flex-row items-center justify-center cursor-pointer px-2 relative z-30 block text-base font-medium text-primary transition-colors group-hover:text-green dark:text-white dark:group-hover:text-secondary">

                        <span>{{ request.user.username }} -> </span>

                        <span class="flex items-center px-1 cursor-pointer lg:my-0"
                        >
                            خروج
                        </span>
                        <form id="logout-form" action="{{ request.scheme }}://{{ request.META.HTTP_HOST }}{% url "customuser:logout" %}" method="POST" style="display: none;">
                            {% csrf_token %}
                        </form>

                        </a>


                    {% endif %}
                </li>

                <li class="mr-4" :title="isDarkMode ? 'حالت روز' : 'حالت شب'">
                    <i
                            class="mdi cursor-pointer text-3xl text-primary dark:text-white"
                            @click="themeSwitch()"
                            :class="isDarkMode ? 'mdi-white-balance-sunny' : 'mdi-weather-night'"
                    ></i>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% include "layouts/sidebar.html" %}

templates/layouts/sidebar.html
<aside
        class="pointer-events-none fixed inset-0 z-50 flex bg-black bg-opacity-80 opacity-0 transition-opacity lg:hidden"
        :class="isMobileMenuOpen ? 'opacity-100 pointer-events-auto' : ''"
>
    <div class="ml-auto w-2/3 bg-green p-4 md:w-1/3">
        <i
                class="mdi mdi-close absolute top-0 left-0 mt-4 ml-4 text-4xl text-white"
                @click="isMobileMenuOpen = false"
        ></i>
        <ul class="pt-10 space-y-3 flex flex-col">

            <li class="">
                {% if not request.user.is_authenticated %}
                <a
                        href="{{ request.scheme }}://{{ request.META.HTTP_HOST }}{% url "customuser:login-or-register" %}"
                        class="mb-3 block px-2 font-body text-lg font-medium text-white"
                >ورود / ثبت نام</a
                >
                    {% else %}
                    <a      onclick="event.preventDefault(); document.getElementById('logout-form').submit();"
                                class="flex flex-row truncate mb-3 block px-2 font-body text-lg font-medium text-white">

                        <span>{{ request.user.username }} -> </span>

                        <span class="flex items-center"
                        >
                            خروج
                        </span>
                        <form id="logout-form" action="{{ request.scheme }}://{{ request.META.HTTP_HOST }}{% url "customuser:logout" %}" method="POST" style="display: none;">
                            {% csrf_token %}
                        </form>

                        </a>
                {% endif %}
            </li>

            <li class="">
                <a
                        href="{{ request.scheme }}://{{ request.META.HTTP_HOST }}{% url "blog:bookmarks" %}"
                        class="mb-3 block px-2 font-body text-lg font-medium text-white"
                >
                    ذخیره‌شده‌ها
                </a>
            </li>

            <li class="">
                <a
                        href="{{ request.scheme }}://{{ request.META.HTTP_HOST }}{% url "blog:all-posts" %}"
                        class="mb-3 block px-2 font-body text-lg font-medium text-white"
                >جدیدترین</a
                >
            </li>

            <li class="">
                <a
                        href="{{ request.scheme }}://{{ request.META.HTTP_HOST }}{% url "website:contact" %}"
                        class="mb-3 block px-2 font-body text-lg font-medium text-white"
                >تماس با ما</a
                >
            </li>

        </ul>
    </div>
</aside>