blog/urls.py
from django.urls import path
from blog.views import *

app_name = 'blog'

urlpatterns = [
    path('<str:slug>-p<int:pid>', show, name='show-post'),
    path('<str:slug>-c<int:cid>', show_category_posts, name='show-category-posts'),
    path('all', all_posts, name='all-posts'),
    path('bookmark', bookmark, name='bookmark'),
    path('bookmarks', bookmarks, name='bookmarks'),
    path('rate/<int:pid>/<int:rate>', rate, name='rate')
]

customuser/urls.py
from django.urls import path
from customuser.views import *

app_name = 'customuser'

urlpatterns = [
    path('', login_or_register, name='login-or-register'),
    path('logout', logout_user, name='logout'),
    path('back-from-google', back_from_google, name='back-from-google')
]

src/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

from blog.sitemaps import BlogSitemap, CategoriesSitemap
from src import settings
from website.sitemaps import StaticViewSitemap

sitemaps = {
    'static': StaticViewSitemap,
    'blog': BlogSitemap,
    'categories': CategoriesSitemap
}

urlpatterns = [
    path('administors/', admin.site.urls),
    path('auth', include('customuser.urls')),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('comment/', include('comment.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', include('robots.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path("", include("allauth.urls"))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website.views import *

app_name = 'website'

urlpatterns = [
    path('', index, name='home'),
    path('contact', contact, name='contact')
]

customuser/models.py
from django.core.paginator import Paginator
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser


# from blog.models import Post


class User(AbstractUser):
    bookmarks = models.ManyToManyField('blog.Post', blank=True)

    class Meta:
        db_table = 'auth_user'

    def get_paginate_bookmarks(self, per_page: int):
        return Paginator(self.bookmarks.all(), per_page)

customuser/views.py
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST, require_GET
from django.shortcuts import render, redirect
from customuser.middlewares import guest


# Create your views here.
@require_GET
@guest
def login_or_register(request):
    return render(request, 'customuser/login-or-register.html')


@login_required
@require_POST
def logout_user(request):
    logout(request)
    return redirect("website:home")


@login_required
def back_from_google(request):
    list(messages.get_messages(request))
    messages.success(request, 'شما با موفقیت وارد شدید!')
    return redirect('blog:all-posts')

templates/customuser/_base.html
{% load compress %}
{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ورود / ثبت نام - سوتا</title>
    <link rel="canonical" href="{{ request.scheme }}://{{ request.META.HTTP_HOST }}{% url "customuser:login-or-register" %}"/>
{#    <link rel="next" href="{{ request.scheme }}://{{ request.META.HTTP_HOST }}{% url "blog:all-posts" %}"/>#}
    <meta property="og:locale" content="fa_IR"/>
    <meta property="og:type" content="website"/>
    <meta property="og:title" content="ورود / ثبت نام - سوتا"/>
    <meta property="og:url" content="{{ request.scheme }}://{{ request.META.HTTP_HOST }}{% url "customuser:login-or-register" %}"/>
    <meta property="og:site_name" content="آموزش مفاهیم برنامه نویسی و طراحی وب - سوتا"/>
    <meta property="og:image" content="{{ request.scheme }}://{{ request.META.HTTP_HOST }}{% static 'img/logo.svg' %}"/>
    <meta property="og:image:secure_url"
          content="{{ request.scheme }}://{{ request.META.HTTP_HOST }}{% static 'img/logo.svg' %}"/>
    <meta property="og:image:width" content="1280"/>
    <meta property="og:image:height" content="720"/>
    <meta property="og:image:type" content="image/svg+xml"/>

    <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.5.0/styles/atom-one-dark.min.css"
    />

    <script src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js" defer></script>

    {% compress css %}
    <link rel="stylesheet" href="{% static 'src/output.css' %}">
    {% endcompress %}

    <link rel="stylesheet" href="{% static 'src/fonts.css' %}">

    <style>
        [x-cloak] {
            display: none;
        }
    </style>

</head>

<body
        x-data="global()"
        x-init="themeInit()"
        :class="isMobileMenuOpen ? 'max-h-screen overflow-hidden relative' : ''"
        class="dark:bg-primary"
        dir="rtl"
>
<div class="w-full mx-auto font-body">
    <div id="main">
        {% block content %}
        {% endblock content %}
    </div>
</div>

<script src="{% static 'src/main.js' %}"></script>
</body>

</html>

templates/customuser/login-or-register.html
{% extends "./_base.html" %}
{% load socialaccount %}
{% load static %}

{% block content %}

    <div class="flex flex-col items-center justify-center w-full h-screen">

    <div class="flex flex-col justify-center items-center dark:bg-blue-dark bg-white lg:w-1/3  md:w-1/2 w-full -mt-20">
        <a href="{% url "website:home" %}" class="rounded-full mb-2">
            <img src="{% static 'img/logo.svg' %}" alt="logo"/>
        </a>
        <h1 class="text-lg dark:text-white text-gray-600 font-bold">
            ورود / ثبت نام
        </h1>
        <a href="{% provider_login_url 'google' %}?next={% url "customuser:back-from-google" %}"
            aria-label="Continue with google" role="button"
           class="flex text-center focus:outline-none focus:ring-2 focus:ring-offset-1 focus:ring-secondary py-3.5 px-4 border rounded-lg border-secondary flex items-center w-auto mt-10">
            <svg width="19" height="20" viewBox="0 0 19 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M18.9892 10.1871C18.9892 9.36767 18.9246 8.76973 18.7847 8.14966H9.68848V11.848H15.0277C14.9201 12.767 14.3388 14.1512 13.047 15.0812L13.0289 15.205L15.905 17.4969L16.1042 17.5173C17.9342 15.7789 18.9892 13.221 18.9892 10.1871Z" fill="#4285F4" />
                <path d="M9.68813 19.9314C12.3039 19.9314 14.4999 19.0455 16.1039 17.5174L13.0467 15.0813C12.2286 15.6682 11.1306 16.0779 9.68813 16.0779C7.12612 16.0779 4.95165 14.3395 4.17651 11.9366L4.06289 11.9465L1.07231 14.3273L1.0332 14.4391C2.62638 17.6946 5.89889 19.9314 9.68813 19.9314Z" fill="#34A853" />
                <path d="M4.17667 11.9366C3.97215 11.3165 3.85378 10.6521 3.85378 9.96562C3.85378 9.27905 3.97215 8.6147 4.16591 7.99463L4.1605 7.86257L1.13246 5.44363L1.03339 5.49211C0.37677 6.84302 0 8.36005 0 9.96562C0 11.5712 0.37677 13.0881 1.03339 14.4391L4.17667 11.9366Z" fill="#FBBC05" />
                <path d="M9.68807 3.85336C11.5073 3.85336 12.7344 4.66168 13.4342 5.33718L16.1684 2.59107C14.4892 0.985496 12.3039 0 9.68807 0C5.89885 0 2.62637 2.23672 1.0332 5.49214L4.16573 7.99466C4.95162 5.59183 7.12608 3.85336 9.68807 3.85336Z" fill="#EB4335" />
            </svg>
            <p class="text-base font-medium mr-4 dark:text-white text-gray-700">ادامه دادن با گوگل</p>
        </a>
    </div>

</div>

{% endblock %}